# Copyright (C) 2026 Maxim [maxirmx] Samsonov (www.sw.consulting)
# All rights reserved.
# This file is a part of Sarafan application

name: sarafan-core

services:
  api:
    build:
      context: .
      dockerfile: src/Sarafan.Core/Dockerfile
    ports:
      - "8080:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
    healthcheck:
      test: ["CMD", "curl", "--fail", "--silent", "http://localhost:8080/api/status/status"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s
